apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-bootstrap-vault
  namespace: eso-operator
spec:
  provider:
    # provider type: azure keyvault
    azurekv:
      # azure tenant ID, see: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant
      tenantId: "c8139620-166b-4186-9a9d-ca6ddc613c96"
      # URL of your vault instance, see: https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates
      vaultUrl: "https://global-bootstrap.vault.azure.net"
      authType: ServicePrincipal
      authSecretRef:
        # points to the secret that contains
        # the azure service principal credentials
        clientId:
          name: eso-spn-secret
          key: ClientID
        clientSecret:
          name: eso-spn-secret
          key: ClientSecret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aso-credentials
  namespace: eso-operator
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-bootstrap-vault

  target:
    name: aso-spn-secret
    creationPolicy: Owner

  data:
    - secretKey: spn-aso-client-id
      remoteRef:
        key: spn-aso-client-id
